default_platform(:ios)

platform :ios do
	desc "Build For Testing"
	lane :build_for_testing do |options|
		scan(
			scheme: "TinkoffEdu2021",
			clean: true,
			build_for_testing: true
		)
	end

	desc "Run Tests"
	lane :run_tests_without_build do |options|
		scan(
			scheme: "TinkoffEdu2021",
			test_without_building: true
		)
		ds_notify_success
	end

	desc "Build And Test"
	lane :build_and_test do |options|
		build_for_testing
		run_tests_without_build
	end

	desc "Send build notification to Discord"
	lane :ds_notify_success do |options|
		discord_notifier(
		    webhook_url: ENV["DISCORD_HOOK"],
		    title: "Build Succed 🎉",
		    description: "All tests Passed",
		    discord_user_id: "7247",
		    image_url: "https://ixbt.online/live/images/original/17/04/81/2021/04/02/c8deac0f9a.jpg?w=877",
		    success: true,
		    fields:[
      			{
        			name:"Author: ", 
        			value:"Kirill Lukianov"
        		}
      		]
  		)
	end

	error do |lane, exception, options|
		discord_notifier(
		    webhook_url: ENV["DISCORD_HOOK"],
		    title: "Build Failed",
		    description: exception.to_s,
		    success: false,
		    discord_user_id: "7247",
		    image_url: "https://i.ytimg.com/vi/21UXJFvpG0I/maxresdefault.jpg",
		    fields:[
      			{
        			name:"Author: ", 
        			value:"Kirill Lukianov"
        		}
      		]
  		)
    end
end
