default_platform(:ios)

platform :ios do
	desc "CI Testing Lab"
	lane :hello do |options|
		puts "Hellow"
	end

	desc "build_for_testing"
	lane :build_for_testing do |options|
		scan(
			scheme: "TinkoffEdu2021",
			clean: true,
			build_for_testing: true
		)
	end

	desc "run_tests"
	lane :run_tests_without_build do |options|
		scan(
			scheme: "TinkoffEdu2021",
			test_without_building: true
		)
	end

	desc "build_and_test"
	lane :build_and_test do |options|
		build_for_testing
		run_tests_without_build
	end
end